### ISSUE TITLE
Suggestions for color improvements

### ISSUE THREAD

**Issue by x12901** [subtheme-pro/solarized#1]
Hello,Your plugin is cool,！The theme I'm using is Solarized Light.There is a problem with this theme. When I use the code completion feature, the color of the selected code is too similar to the background and I can't tell which is my selected code!

**Comment by jontaydev** [comment]
Ah thanks for pointing this out. The theme is still pretty new and I haven't had time to go through all of the syntax yet. I'll have that fixed by this weekend (along with some other fixes like button background color issues), but let me know if you see anything else in the meantime.

**Comment by jontaydev** [comment]
Hey, I wasn't able to see the issue you mentioned (on PyCharm). Could you send a screenshot? Sorry I didn't get to this sooner.
