### ISSUE TITLE
Can't see buttons when upgrading extensions

### ISSUE THREAD

**Issue by x12901** [subtheme-pro/solarized#2]
Great Theme! When the extension prompts for an upgrade, I can't read the words on the button, the whole button is grayed out.
![image](https://user-images.githubusercontent.com/30824839/101302374-695e0d80-3876-11eb-86ef-deaa1c10522a.png)

https://github.com/x12901/error/blob/master/Screenshot%202020-12-07%20101954.png?raw=true

**Comment by jontaydev** [comment]
Sorry for the late response, just pushed an update (0.4) to the plugin repo which should fix this issue. Let me know if your seeing any other issues once the update comes in.

Thanks
