### ISSUE TITLE
Parameter Info tip background

### ISSUE THREAD

**Issue by dxps** [subtheme-pro/solarized#4]
Although similar with the previous (#3 ) issue, having in common the same gray background that breaks the contrast, I want to raise it as a distinct thing to improve.

Parameters info (accessible using `Ctrl/Cmd+P` shortcut or `View > Parameter Info` menu) background needs some improvement (basically having it darker):

![image](https://user-images.githubusercontent.com/14140226/113488764-b2db0400-94c8-11eb-9a71-b382eb529aec.png)

And thank you for making such a nice theme! :smile:

**Comment by jontaydev** [comment]
Fixed, will be available in the 1.1 update when it gets approved in the next few days. (I couldn't reproduce #3, need to figure out how to show that one.)
