### ISSUE TITLE
Kotlin smart cast background

### ISSUE THREAD

**Issue by ubuntudroid** [subtheme-pro/solarized#5]
**Describe the bug**
Kotlin smart casts in Solarized Light are really hard to read and at the same time pop out from the rest of the code disproportionally.

**To Reproduce**
1. Clone [this repository](https://github.com/ubuntudroid/SolarizedSmartCastIssueSample)
2. Open `SmartCastIssueSample.kt` with the light theme enabled and observe the highlighting of `test` in line 4

**Screenshots**
![CleanShot 2021-05-05 at 12 05 22](https://user-images.githubusercontent.com/519867/117125718-33c43e80-ad9a-11eb-976c-0910acaba961.png)

**Application:**
Tested in IntelliJ CE and Android Studio

**Comment by jontaydev** [comment]
Looks like an easy fix, I'll try to get an update pushed before the weekend.

**Comment by jontaydev** [comment]
Sorry for the delay (smart cast coloring wasn't showing up until I figured out how to configure the android sdk). Should be approved in a few days: https://plugins.jetbrains.com/plugin/14920-solarized-theme/versions/stable/120206
